site_name: UNIST STEM-CAMP Website
theme: readthedocs

page:
  - Home: index.md
  - Lab1:
    - Linux : 'Lab1/Linux_Manual.md'
  - Lab2:
    - ROS : 'Lab2/ROS_Manual.md'
  - Lab3:
    - Python : 'Lab3/Python_Class_Manual.md'
  - Lab4:
    - Tello : 'Lab4/Tello_Manual.md'
  - Lab5:
    - Color Segmentation : 'Lab5/Color Segmentation.md'
    - Line Following : 'Lab5/Line Follwoing.md'
  - Lab6:
  - Tello: Tello_Manual.md
  - Python: Python_Class_Manual.md
