site_name: UNIST STEM-CAMP Website
theme: readthedocs

page:
  - Home: index.md
  - Lab1:
    - Linux_Manual : 'Lab1/Linux_Manual.md'
  - Lab2:
    - ROS_Manual : 'Lab2/ROS_Manual.md'
  - Lab3:
    - Python_Class_Manual : 'Lab3/Python_Class_Manual.md'
  - Lab4:
    - Tello_Manual : 'Lab4/Lab4.md'
  - Lab5:
    - Color Segmentation : 'Lab5/Color Segmentation.md'
    - Line Following : 'Lab5/Line Follwoing.md'
  - Lab6:
  - Tello_Manual: Tello_Manual.md
  - Python_Class: Python_Class_Manual.md
